version: '2.3'
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: "zookeeper"
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: "kafka"
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "echo 127.0.0.1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  redis:
    container_name: redis-integration-test-ar
    image: redis:5.0.4
    ports:
      - "6379:6379"

  twitter_fetcher:
    container_name: twitter_fetcher
    build: ./twitter_fetcher

  twitter_preprocess:
    container_name: twitter_preprocess
    build: ./twitter_preprocess
#    command: sh -c "python -u twitter_crowler.py"

